apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: gitlab
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    tier: backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: gitlab
spec:
  selector:
    matchLabels: 
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      volumes:
      -  name: redis
         persistentVolumeClaim:
           claimName: redis-claim   
      containers:
        - image: redis:3.0.7-alpine
          name: redis
          ports:
          - containerPort: 6379
            name: redis
          volumeMounts:
          - mountPath: "/data"
            name: redis

